#include "dealer.h"
#include "constants.h"
#include "cards.h"

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

unsigned int nano_seed(void)
{   // Generated by AI, 11/15/25
    struct timespec seed;
    if (clock_gettime(CLOCK_MONOTONIC, &seed) == -1)
    {
        perror("clock_gettime error");
    }
    unsigned int seedOut = (unsigned int)(seed.tv_sec ^ seed.tv_nsec);
    return seedOut;
}

int basic_RNG(unsigned int seed, int rangeStart, int rangeEnd)
{
    int output = 0;
    srand(seed);
    output = (rand() % (rangeEnd - rangeStart)) + rangeStart;
    return output;
}

int* list_RNG(int length, int rangeStart, int rangeEnd)
{
    int* listOut = malloc(sizeof(int) * length + (NULL_TERM * sizeof(int)));

    int incrementer;
    for (incrementer = 0; incrementer < length; incrementer++)
    {
        int number = basic_RNG(nano_seed(), rangeStart, rangeEnd);
        listOut[incrementer] = number;
    }
    
    return listOut;
}

// void undupe_int(Card **deck, Card *hand, int handSize)
// {
//     for (int i = 0; i < handSize; i++)
//     {
//         while ( && j != i)
//         {
//             hand[j].
//         }
//     }
// }

Card* hand_generate(Card **deck, int handSize)
{
    Card *handOut = malloc(sizeof(Card) * handSize + (NULL_TERM * sizeof(Card)));
    int *suitRNG = list_RNG(handSize, 0, NUMBER_SUITS);
    int *cardRNG = list_RNG(handSize, 0, SIZE_SUIT);

    
    for (int i = 0; i < handSize; i++)
    {
        Card *ptrCard = &deck[suitRNG[i]][cardRNG[i]];
        for (int j = 0; j < NUMBER_SUITS && ptrCard->drawn; j++)
        {
            ptrCard = &deck[suitRNG[i + j]][cardRNG[i + j]];
        }
        handOut[i] = *ptrCard;
        ptrCard->drawn = true;
    }

    free(suitRNG);
    free(cardRNG);

    return handOut;
}