#include "constants.h"
#include "cards.h"
#include "dealer.h"

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <time.h>

int inputHandler(int *variable);
void inputPrompt(int *variable, char *prompt);

int main(void)
{
    Card **playerDeck = deck_construct();
    if (playerDeck == NULL) {return -1;}
    
    int userInput = 0;
    char *prompt1 =
        "1. Generate Hand\n"
        "2. See Deck\n"  
        "3. See Card\n"
        "9. Exit\n";
    inputPrompt(&userInput, prompt1);
    
    while (userInput != EXIT)
    {
        enum Menu
        {
            HAND = 1,
            SEEDECK,
            SEECARD
        };

        switch (userInput)
        {
            case HAND:
            {
                int userHand = 0;
                inputPrompt(&userHand, "How many cards in your hand?");
                Card *hand = hand_generate(playerDeck, userHand);
                printf("\n\n*****\nHAND\n*****\n");
                for (int i = 0; i < userHand; i++)
                {
                    printf("Suit: %s, Rank: %s, Drawn: %d\n", hand[i].suit, hand[i].rank_string, hand[i].drawn);
                }
            }
            break;
            case SEEDECK:
            {
                printDeck(Card **playerDeck);
            }
            break;
            case SEECARD:
            {
                int userSuit = 0;
                int userRank = 0;
                inputPrompt(&userSuit, "Which suit? (AS AN INTEGER)");
                inputPrompt(&userRank, "Which rank? (AS AN INTEGER)");
                printf("Suit %s, Rank: %s, Value: %d, Drawn: %d\n", playerDeck[userSuit-1][userRank-1].suit, playerDeck[userSuit-1][userRank-1].rank_string, playerDeck[userSuit-1][userRank-1].value_base, playerDeck[userSuit-1][userRank-1].drawn);
            }
        }

        inputPrompt(&userInput, prompt1);
    }


    /* DEBUG */
    // printf("\n");
    // for (int i = 0; i < 5; i++)
    // {
    //     printf("Suit: %s, Rank: %s, Drawn: %d\n", hand[i].suit, hand[i].rank_string, hand[i].drawn);
    // }
    // printf("\n\n*****\nDECK\n*****");
    // for (int i = 0; i < NUMBER_SUITS; i++)
    // {
    //     printf("\nSuit: %s\n", SUITS[i]);
    //     for (int j = 0; j < SIZE_SUIT; j++)
    //     {
    //         // printf("Rank: %s, Value: %d, Drawn: %d\n", playerDeck[i][j].rank_string, playerDeck[i][j].value_base, playerDeck[i][j].drawn);
    //         if (playerDeck[i][j].drawn)
    //         {
    //             printf("Rank: %s, Value: %d, Drawn: %d\n", playerDeck[i][j].rank_string, playerDeck[i][j].value_base, playerDeck[i][j].drawn);
    //         }
    //     }
    // }
    /* endDB */

    for (int i = 0; i < NUMBER_SUITS; i++)
    {
        free(playerDeck[i]);
    }
    free(playerDeck);
    return 0;
}

void printDeck(Card **deck)
[
    printf("\n\n*****\nDECK\n*****");
    for (int i = 0; i < NUMBER_SUITS; i++)
    {
        printf("\nSuit: %s\n", SUITS[i]);
        for (int j = 0; j < SIZE_SUIT; j++)
        {
            printf("Rank: %s, Value: %d, Drawn: ", deck[i][j].rank_string, deck[i][j].value_base);
            if (deck[i][j].drawn)
            {
                printf("true\n");
            }
            else
            {
                printf("false\n");
            }
        }
    }
}

int inputHandler(int *variable)
{   
    int status = 0;
    int ch;
    status = scanf("%d", variable);
    if (status != 1)
    {
        while ((ch = getchar()) != '\n' && ch != EOF)
            ; // Clear buffer; generated by AI, (unknown date)
    }
    return status;
}

void inputPrompt(int *variable, char *prompt)
{
    do
    {
        printf("%s\n==> ", prompt);
    } while (inputHandler(variable) != 1);
    return;
}
