#include "constants.h"
#include "cards.h"
#include "dealer.h"

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <time.h>

void printDeck(Card **deck);
int inputHandler(int *variable);
void inputPrompt(int *variable, char *prompt);

int main(void)
{
    Card **playerDeck = deck_construct();
    if (playerDeck == NULL) {return -1;}
    
    int userInput = 0;
    char *prompt1 =
        "1. Generate Hand\n"
        "2. See Deck\n"  
        "3. See Card\n"
        "9. Exit\n";
    inputPrompt(&userInput, prompt1);
    
    while (userInput != EXIT)
    {
        enum Menu
        {
            HAND = 1,
            SEEDECK,
            SEECARD
        };

        switch (userInput)
        {
            case HAND:
            {
                int userHand = 0;
                inputPrompt(&userHand, "How many cards do you want in your hand?");
                Card *hand = hand_generate(playerDeck, userHand);
                printf("\n\n*****\nHAND\n*****\n");
                for (int i = 0; i < userHand; i++)
                {
                    printf("Suit: %s, Rank: %s, Drawn: %d\n", hand[i].suit, hand[i].rank_string, hand[i].drawn);
                }
            }
            break;
            case SEEDECK:
                printDeck(playerDeck);
            break;
            case SEECARD:
            {
                int userSuit = 0;
                int userRank = 0;
                inputPrompt(&userSuit, "Which suit?\n1: Spades\n2: Clubs\n3: Hearts\n4: Diamonds");
                inputPrompt(&userRank, "Which rank? (AS AN INTEGER, 1-13)\nA, 2, 3,...J, Q, K");
                // Alignment with lists
                userSuit-=1;
                userRank = (userRank + 11) % SIZE_SUIT;
                printf("Suit %s, Rank: %s, Value: %d, Drawn: %d\n", playerDeck[userSuit][userRank].suit, playerDeck[userSuit][userRank].rank_string, playerDeck[userSuit][userRank].value_base, playerDeck[userSuit][userRank].drawn);
            }
        }

        inputPrompt(&userInput, prompt1);
    }

    for (int i = 0; i < NUMBER_SUITS; i++)
    {
        free(playerDeck[i]);
    }
    free(playerDeck);
    return 0;
}

void printDeck(Card **deck)
{
    printf("\n\n*****\nDECK\n*****");
    for (int i = 0; i < NUMBER_SUITS; i++)
    {
        printf("\nSuit: %s\n", SUITS[i]);
        for (int j = 0; j < SIZE_SUIT; j++)
        {
            printf("Rank: %s, Value: %d, Drawn: ", deck[i][j].rank_string, deck[i][j].value_base);
            if (deck[i][j].drawn)
            {
                printf("true\n");
            }
            else
            {
                printf("false\n");
            }
        }
    }
}

int inputHandler(int *variable)
{   
    int status = 0;
    int ch;
    status = scanf("%d", variable);
    if (status != 1)
    {
        while ((ch = getchar()) != '\n' && ch != EOF)
            ; // Clear buffer; generated by AI, (unknown date)
    }
    return status;
}

void inputPrompt(int *variable, char *prompt)
{
    do
    {
        printf("%s\n==> ", prompt);
    } while (inputHandler(variable) != 1);
    return;
}
